project_name: diffusion
dataset: cifar10
epochs: 50
batch_size: 128
learning_rate: 0.0003
device: cuda
seed: 42
in_channels: 3
out_channels: 3
resize: [32, 32]
conditioning_dim: 128
layers: [64, 128, 256, 256]
attention_layers: [128, 256]
dropout: 0.1
num_heads: 8
diffusion_steps: 1000
diffusion_schedule: cosine
ema_decay: 0.9999
log_interval: 100
save_interval: 5
model_save_path: ./models/
use_wandb: false
