project_name: diffusion
dataset: mnist
epochs: 10
batch_size: 128
learning_rate: 0.001
device: cpu
seed: 42
in_channels: 1
out_channels: 1
resize: [32, 32]
conditioning_dim: 64
layers: [32, 64, 128]
attention_layers: [64]
dropout: 0.0
num_heads: 4
diffusion_steps: 500
diffusion_schedule: linear
ema_decay: 0.999
log_interval: 50
save_interval: 5
model_save_path: ./models/
use_wandb: false
